---
- name: Setup & install required applications & services
  hosts: servers
  vars:
    # Override these in Command-line
    tailscale_env:
      TS_AUTHKEY: ts-authkey
  tasks:
    - name: Run Tailscale Docker Container in System Container
      become: yes
      environment: "{{ tailscale_env }}"
      shell: |
        docker run -d \
          --name=tailscaled \
          -v /var/lib:/var/lib \
          -v /dev/net/tun:/dev/net/tun \
          --network=host \
          --cap-add=NET_ADMIN \
          --cap-add=NET_RAW \
          --env TS_AUTHKEY="{{ TS_AUTHKEY }}" \
          tailscale/tailscale
